version: '3'
services:
    # my-app:
    # image: ${docker-registry}/my-app:1.0
    # ports:
    # - 3000:3000
    mongodb:
        container_name: mongo-dev
        image: mongo
        ports:
            - '27017:27017'
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=password
        volumes:
            - mongo-data:/data/db
        networks:
            - mongo-compose-network
    mongo-express:
        container_name: mongo-express
        image: mongo-express
        depends_on:
            - mongodb
        networks:
            - mongo-compose-network
        restart: always # fixes MongoNetworkError when mongodb is not ready when mongo-express starts
        ports:
            - '8080:8081'
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
            - ME_CONFIG_MONGODB_ADMINPASSWORD=password
            - ME_CONFIG_MONGODB_SERVER=mongodb
networks:
    mongo-compose-network:
        driver: bridge
volumes:
    mongo-data:
        driver: local
