version: '3'
services:
    my-app:
        image: 557510779509.dkr.ecr.us-east-1.amazonaws.com/my-app:1.0
        ports:
            - '3000:3000'
        networks:
            - mongo-compose-network
    mongodb:
        container_name: mongo-dev
        image: mongo
        ports:
            - '27017:27017'
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=password
        networks:
            - mongo-compose-network
    mongo-express:
        container_name: mongo-express
        image: mongo-express
        depends_on:
            - mongodb
        networks:
            - mongo-compose-network
        ports:
            - '8080:8081'
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongo-dev
            - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
            - ME_CONFIG_MONGODB_ADMINPASSWORD=password
            - ME_CONFIG_MONGODB_SERVER=mongodb

networks:
    mongo-compose-network:
        driver: bridge
